name: qoima
description: Мобильное приложение для учёта склада обуви.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  firebase_core: ^4.9.0
  cloud_firestore: ^6.4.1
  firebase_auth: ^6.5.1
  http: ^1.2.1
  image_picker: ^1.1.2
  file_picker: ^8.1.4
  intl: ^0.20.2
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1
  qr_flutter: ^4.1.0
  shimmer: ^3.0.0
  confetti: ^0.7.0
  google_fonts: ^6.2.1
  fl_chart: ^0.68.0
  pdf: ^3.10.8
  printing: ^5.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.png"
