name: qoima
description: Мобильное приложение для учёта склада обуви.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.1
  firebase_auth: ^5.1.4
  http: ^1.2.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/logo.png
