// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7pCs2kKXhUMgbyvHnl-kQ3bmSY-SSjdk',
    appId: '1:536773855283:web:82c0aadc9ef2cba81e7b46',
    messagingSenderId: '536773855283',
    projectId: 'qoima-61cbb',
    authDomain: 'qoima-61cbb.firebaseapp.com',
    storageBucket: 'qoima-61cbb.firebasestorage.app',
    measurementId: 'G-92Z6VC7JVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoY-rdKvdNrctpnGXIeWgbkckhm4y8wIg',
    appId: '1:536773855283:android:5800d6f03899961a1e7b46',
    messagingSenderId: '536773855283',
    projectId: 'qoima-61cbb',
    storageBucket: 'qoima-61cbb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDotSCA6tjhHjEHLSAqw2JX0a1vTEHWJVo',
    appId: '1:536773855283:ios:33d46d5ac3ffe4661e7b46',
    messagingSenderId: '536773855283',
    projectId: 'qoima-61cbb',
    storageBucket: 'qoima-61cbb.firebasestorage.app',
    iosBundleId: 'com.jambyl.qoima.qoima',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDotSCA6tjhHjEHLSAqw2JX0a1vTEHWJVo',
    appId: '1:536773855283:ios:33d46d5ac3ffe4661e7b46',
    messagingSenderId: '536773855283',
    projectId: 'qoima-61cbb',
    storageBucket: 'qoima-61cbb.firebasestorage.app',
    iosBundleId: 'com.jambyl.qoima.qoima',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7pCs2kKXhUMgbyvHnl-kQ3bmSY-SSjdk',
    appId: '1:536773855283:web:dc0a954b9dcafa581e7b46',
    messagingSenderId: '536773855283',
    projectId: 'qoima-61cbb',
    authDomain: 'qoima-61cbb.firebaseapp.com',
    storageBucket: 'qoima-61cbb.firebasestorage.app',
    measurementId: 'G-TYY8K2X0WW',
  );
}
